version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: notification-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped

  worker:
    build:
      context: ./Backend
    container_name: notification-worker
    command: python receiver.py
    volumes:
      - ./Backend:/app
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ messaging
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
